site_name: MkDocs Placeholder Plugin
repo_url: https://github.com/six-two/mkdocs-placeholder-plugin
repo_name: mkdocs-placeholder-plugin

theme:
  name: material
  # name: mkdocs
  # name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.sections
  - content.code.copy
  - navigation.footer
plugins:
- placeholder:
    placeholder_extra_js: placeholder-extra.js
- badges
- search

nav:
- index.md
- usage.md
- demo.md
- configuration.md
- advanced-usage.md
- replace-modes.md
- validators.md
- themes.md
- "Tests":
  - tests/basic.md
  - tests/auto-tables.md
  - tests/auto-table-empty.md
  - tests/mermaid_diagrams.md
  - tests/validators.md
  - tests/new-ts-code.md

extra_javascript:
- development-warning.js

markdown_extensions:
  # Message/error/warning boxes
  - admonition
  - pymdownx.details
  # For search exclusion
  - attr_list
  # For mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # for tabs
  - pymdownx.tabbed:
      alternate_style: true

watch:
- placeholder-plugin.yaml
